version: '3'

services:
  app:
    build:
      context: node
    volumes:
      - ./node/:/usr/src/app
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    tty: true
    ports:
      - 3000:3000
    networks:
      - app-proxy-reverse
    depends_on:
      - db

  db:
    networks:
      - app-proxy-reverse
    image: mysql:latest
    container_name: db
    command: --innodb-use-native-aio=0
    volumes:
    - ./mysql/:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=app-proxy-reverse
      - MYSQL_ROOT_PASSWORD=root
    tty: true
    restart: always

  nginx:
    container_name: nginx
    restart: always
    build: 
      context: nginx
    # entrypoint: dockerize -wait tcp://app:3000 -timeout 20s docker-entrypoint.sh
    ports:
      - 8080:80
    depends_on:
      - app
    networks:
      - app-proxy-reverse

networks:
  app-proxy-reverse:
    driver: bridge
    
