version: '3'

services:
  app:
    build:
      context: node
    volumes:
      - ./node/:/usr/src/app
    container_name: lucasivisson/nodejs-proxy-reverse
    tty: true
    ports:
      - 3000:3000

    db:
      build:
        context: mysql
      tty: true
      restart: always
    
