version: '3'

services:
  laravel:
    image: lucasivisson/laravel
    container_name: laravel
    networks:
      - laranet

  nginx:
    image: lucasivisson/nginx-fullcycle
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"

networks:
  laranet:
    driver: bridge
    